"""The application page box instance names."""

FOREIGN_BOX = 'foreign_box'
FOREIGN_CREATE_BOX = 'foreign_create_box'
FOREIGN_EXERCISE_BOX = 'foreign_exercise_box'
FOREIGN_LIST_BOX = 'foreign_list_box'
FOREIGN_PARAMS_BOX = 'foreign_params_box'
FOREIGN_UPDATE_BOX = 'foreign_update_box'
GLOSSARY_BOX = 'glossary_box'
GLOSSARY_EXERCISE_BOX = 'glossary_exercise_box'
GLOSSARY_PARAMS_BOX = 'glossary_exercise_params_box'
LOGIN_BOX = 'login_box'
MAIN_BOX = 'main_box'
USER_BOX = 'user_box'
USER_CREATE_BOX = 'user_create_box'
USER_UPDATE_BOX = 'user_update_box'
